version: '2'
services:
  pihole:
    extends:
      service: pihole
      file: pihole/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${PIIPV4}
  portainer:
    extends:
      service: portainer
      file: portainer/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${PORTIPV4}
  lazydocker:
    extends:
      service: lazydocker
      file: lazy/docker-compose.yaml
    networks:
      home: # NO IP Address Required but stops docker-compose creating a second service_default macvlan
        
networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.192/27
