version: '2'
services:
  pihole:
    extends:
      service: pihole
      command: sh -c "env; sleep 900"
      file: pihole/docker-compose.yaml
    networks:
      home:
        ipv4_address: 192.168.1.201

  lazydocker:
    extends:
      service: lazydocker
      file: lazy/docker-compose.yaml
    networks:
      home:
        
networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.192/27
