version: '2'
services:
  hass:
    extends:
      service: hass
      file: hass/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${HASSIPV4}
  deCONZ:
    extends:
      service: deCONZ
      file: deconz/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${DECONZIPV4}
  pihole:
    extends:
      service: pihole
      file: pihole/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${PIIPV4}
  portainer:
    extends:
      service: portainer
      file: portainer/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${PORTIPV4}
  autoyoutube:
    extends:
      service: autoyoutube
      file: auto-YouTube/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${AUTOYTIPV4}
  lazydocker:
    extends:
      service: lazydocker
      file: lazy/docker-compose.yaml
    networks:
      home: # NO IP Address Required but stops docker-compose creating a second service_default macvlan
  phpipam:
    depends_on:
      - mysql
    extends:
      service: phpipam
      file: phpipam/docker-compose.yaml
    networks:
      home:
        ipv4_address: ${PHPIPAMV4}
  mysql:
    extends:
      service: mysql
      file: mysql/docker-compose.yaml
    networks:
      home: # NO IP Address Required but stops docker-compose creating a second service_default macvlan
  # web:
  #   depends_on:
  #     - web-be1
  #     - web-be2
  #   extends:
  #     service: web-fe0
  #     file: web/docker-compose.yaml 
  #   networks:
  #     home:
  #       ipv4_address: ${WEBIPV4}
  # web-be1:
  #   extends:
  #     service: web-be1
  #     file: web/docker-compose.yaml 
  #   networks:
  #     home:
  #       ipv4_address: ${WEBBE1IPV4}
  # web-be2:
  #   extends:
  #     service: web-be2
  #     file: web/docker-compose.yaml 
  #   networks:
  #     home:
  #       ipv4_address: ${WEBBE2IPV4}

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.192/27
