version: '2'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.0
    hostname: pihole
    domainname: farmerbean.dev
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.1.201
      WEBPASSWORD: password
      VIRTUAL_HOST: pihole.farmerbean.dev
      DNS1: 127.0.0.1
      DNS2: 9.9.9.11
      DNSMASQ_LISTENING: all
      TZ: "Europe/Amsterdam"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/pihole/pihole-configs:/etc/pihole
      - /volume2/docker/pihole/dnsmasq.d-configs:/etc/dnsmasq.d
      - /volume2/docker/pihole/pihole-configs/external.conf:/etc/lighttpd/external.conf:ro
      - /volume2/docker/certs:/home/pi/certs:ro
    restart: always
