version: "2"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    hostname: ${ADHOST}
    domainname: ${DOMAINNAME}
    cap_add:
      - NET_ADMIN
    ports:
      - 53/tcp
      - 53/udp
      - 784/udp
      - 853/tcp
      - 3000/tcp
      - 80/tcp
      - 443/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERHOME}/adguard/workdir:/opt/adguardhome/work
      - ${DOCKERHOME}/adguard/conf:/opt/adguardhome/conf
      - ${CERTHOME}:/opt/adguardhome/certs:ro
    environment:
      ServerIP: ${ADGUARDIPV4}
      VIRTUAL_HOST: ${ADHOST}.${DOMAINNAME}
      DNSMASQ_LISTENING: localonly
      TZ: "Europe/Amsterdam"
    restart: always