version: '2'
services:
  autoyoutube:
    image: tzahi12345/youtubedl-material:latest
    container_name: auto-YouTube
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERHOME}/autoyt/downloads:/app/downloads
      - ${CERTHOME}:/certs:ro
      - ${DOCKERHOME}/autoyt/config:/app/config
      - ${DOCKERHOME}/autoyt/appdaata:/app/appdata
      - ${DOCKERHOME}/autoyt/audio:/app/audio
      - ${DOCKERHOME}/autoyt/subscriptions:/app/subscriptions
      - ${DOCKERHOME}/autoyt/users:/app/users
      - ${DOCKERHOME}/autoyt/video:/app/video
    environment:
      - PUID=1234
      - PGID=5678
      - UMASK_SET=022
    ports:
    - 8998:17442
volumes:
  downloads:
  config: