version: '2'
services:
  autoyoutube:
    image: tzahi12345/youtubedl-material:nightly
    container_name: auto-YouTube
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERHOME}/autoyt/downloads:/app/downloads
      - ${CERTHOME}:/certs:ro
      - ${DOCKERHOME}/autoyt/config:/app/config
      - ${DOCKERHOME}/autoyt/appdata:/app/appdata
      - ${DOCKERHOME}/autoyt/audio:/app/audio
      - ${DOCKERHOME}/autoyt/subscriptions:/app/subscriptions
      - ${DOCKERHOME}/autoyt/users:/app/users
      - ${DOCKERHOME}/autoyt/video:/app/video
    environment:
      - PUID=1000
      - PGID=1000
    environment: 
      ALLOW_CONFIG_MUTATIONS: 'true'
    ports:
      - 8998:17442
volumes:
  downloads:
  config: